#--------------------------pod私有源--------------------------------------
#source 'git@github.com:zengzhihui/gz_pod_specs.git'
source  'https://github.com/zengzhihui/gz_pod_specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

def appPods
    pod 'GZUIBase',:path => '../'
end

target 'GZUIBase' do
    appPods
end

